"""add is_automated column to document_extraction_reviews

Revision ID: 20260417_000009
Revises: 20260331_000008
Create Date: 2026-04-17 00:00:09.000000

Adds is_automated flag to distinguish auto-verdicts (generated by the
high-confidence extraction path) from human reviews. Auto-verdicts are
inserted with reviewer_email='<automated>', verdict='correct',
reasoning='<automated>'. The analytics summary breaks these out.
"""

from alembic import op


revision = "20260417_000009"
down_revision = "20260331_000008"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
        ALTER TABLE public.document_extraction_reviews
        ADD COLUMN IF NOT EXISTS is_automated BOOLEAN NOT NULL DEFAULT false
        """
    )

    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_extraction_reviews_is_automated
        ON public.document_extraction_reviews(is_automated)
        """
    )


def downgrade():
    op.execute("DROP INDEX IF EXISTS public.idx_extraction_reviews_is_automated")
    op.execute(
        "ALTER TABLE public.document_extraction_reviews DROP COLUMN IF EXISTS is_automated"
    )
